// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAorSRAONvC26F7J4i6BaYH6onJhQVAe2s',
    appId: '1:7487890900:web:b806eb352340f488f4a241',
    messagingSenderId: '7487890900',
    projectId: 'ai-exam-2a2a4',
    authDomain: 'ai-exam-2a2a4.firebaseapp.com',
    storageBucket: 'ai-exam-2a2a4.firebasestorage.app',
    measurementId: 'G-527PWPK63N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKvxQWZNt5aN23-yl54Taw__af9Nh2K7s',
    appId: '1:7487890900:android:99b739de9a43a4b7f4a241',
    messagingSenderId: '7487890900',
    projectId: 'ai-exam-2a2a4',
    storageBucket: 'ai-exam-2a2a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg_zVpE4Vwaf6zB5yhlZCBjC-GpyKuEFE',
    appId: '1:7487890900:ios:eb192dfde3c1312df4a241',
    messagingSenderId: '7487890900',
    projectId: 'ai-exam-2a2a4',
    storageBucket: 'ai-exam-2a2a4.firebasestorage.app',
    iosBundleId: 'com.example.aiExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg_zVpE4Vwaf6zB5yhlZCBjC-GpyKuEFE',
    appId: '1:7487890900:ios:eb192dfde3c1312df4a241',
    messagingSenderId: '7487890900',
    projectId: 'ai-exam-2a2a4',
    storageBucket: 'ai-exam-2a2a4.firebasestorage.app',
    iosBundleId: 'com.example.aiExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAorSRAONvC26F7J4i6BaYH6onJhQVAe2s',
    appId: '1:7487890900:web:eb3926e46c51b968f4a241',
    messagingSenderId: '7487890900',
    projectId: 'ai-exam-2a2a4',
    authDomain: 'ai-exam-2a2a4.firebaseapp.com',
    storageBucket: 'ai-exam-2a2a4.firebasestorage.app',
    measurementId: 'G-TPFP0K1B44',
  );
}
